In [1]:
import pandas as pd
df = pd.read_csv('quick_commerce_data_raw.csv')

In [2]:
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Noida,46,702.33750,19.182,11.97,12.0,Dairy,Wallet,2.1,1,3.2
1,1000002,Flipkart Minutes,Amritsar,56,1007.30000,19.644,12.74,10.0,Snacks,Cash on Delivery,2.3,0,3.2
2,1000003,Flipkart Minutes,Mumbai,18,1211.66000,16.910,4.85,NaN,Personal Care,Cash on Delivery,3.3,0,3.8
3,1000004,Swiggy Instamart,Delhi,23,1179.05925,5.864,6.44,2.0,Dairy,Credit Card,5.0,1,5.0
4,1000005,Dunzo,Mumbai,44,586.02550,12.470,2.45,13.0,Household,Wallet,3.7,0,4.8

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   Order_ID                 1000000 non-null  int64
 1   Company                  1000000 non-null  str
 2   City                     948000 non-null   str
 3   Customer_Age             1000000 non-null  int64
 4   Order_Value              1000000 non-null  float64
 5   Delivery_Time_Min        1000000 non-null  float64
 6   Distance_Km              1000000 non-null  float64
 7   Items_Count              965000 non-null   float64
 8   Product_Category         1000000 non-null  str
 9   Payment_Method           1000000 non-null  str
 10  Customer_Rating          953000 non-null   float64
 11  Discount_Applied         1000000 non-null  int64
 12  Delivery_Partner_Rating  895863 non-null   float64
dtypes: float64(6), int64(3), str(4)
memory usage: 99.2 MB

In [4]:
#describe() function for statistics only numeric column
df.describe()

,Order_ID,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
count,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,965000.000000,953000.000000,1000000.000000,895863.000000
mean,1.500000e+06,38.470387,571.643584,16.452412,7.750231,9.998317,3.042072,0.400883,3.749257
std,2.886753e+05,12.118520,382.784520,6.257172,4.186665,5.478725,1.186872,0.490078,0.722121
min,1.000001e+06,18.000000,50.000000,5.000000,0.500000,1.000000,1.000000,0.000000,2.500000
25%,1.250001e+06,28.000000,287.840150,12.368000,4.130000,5.000000,2.000000,0.000000,3.100000
50%,1.500000e+06,38.000000,531.324600,16.342000,7.740000,10.000000,3.000000,0.000000,3.700000
75%,1.750000e+06,49.000000,796.182500,20.196000,11.380000,15.000000,4.000000,1.000000,4.400000
max,2.000000e+06,59.000000,13877.325000,40.000000,15.000000,19.000000,5.000000,1.000000,5.000000

In [5]:
#null values
df.isnull().sum()

Order_ID                        0
Company                         0
City                        52000
Customer_Age                    0
Order_Value                     0
Delivery_Time_Min               0
Distance_Km                     0
Items_Count                 35000
Product_Category                0
Payment_Method                  0
Customer_Rating             47000
Discount_Applied                0
Delivery_Partner_Rating    104137
dtype: int64

In [6]:
df['Items_Count'] = df.groupby('Product_Category')['Items_Count'].transform(
    lambda x: x.fillna(x.median())
)

In [7]:
df['Customer_Rating'] = df.groupby('Product_Category')['Customer_Rating'].transform(
    lambda x: x.fillna(x.median())
)

In [8]:
df['Delivery_Partner_Rating'] = df.groupby('Product_Category')['Delivery_Partner_Rating'].transform(
    lambda x: x.fillna(x.median())
)

In [9]:
df.isnull().sum()

Order_ID                       0
Company                        0
City                       52000
Customer_Age                   0
Order_Value                    0
Delivery_Time_Min              0
Distance_Km                    0
Items_Count                    0
Product_Category               0
Payment_Method                 0
Customer_Rating                0
Discount_Applied               0
Delivery_Partner_Rating        0
dtype: int64

In [10]:
df['City'] = df.groupby('Product_Category')['City'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown')
)

In [11]:
df.isnull().sum()

Order_ID                   0
Company                    0
City                       0
Customer_Age               0
Order_Value                0
Delivery_Time_Min          0
Distance_Km                0
Items_Count                0
Product_Category           0
Payment_Method             0
Customer_Rating            0
Discount_Applied           0
Delivery_Partner_Rating    0
dtype: int64

In [12]:
#removing spaces and convert snack case
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [13]:
df.columns

Index(['order_id', 'company', 'city', 'customer_age', 'order_value',
       'delivery_time_min', 'distance_km', 'items_count', 'product_category',
       'payment_method', 'customer_rating', 'discount_applied',
       'delivery_partner_rating'],
      dtype='str')

In [14]:
#distance_km convert to a 4 labels
labels = ['Very_Near', 'Near', 'Far', 'Very_Far']
df['distance_group'] = pd.qcut(df['distance_km'], q=4, labels=labels)
df[['distance_km','distance_group']].head(10)

   distance_km distance_group
0        11.97       Very_Far
1        12.74       Very_Far
2         4.85           Near
3         6.44           Near
4         2.45      Very_Near
5         1.23      Very_Near
6        12.46       Very_Far
7         4.86           Near
8        10.29            Far
9         3.73      Very_Near

In [15]:

df['partner_rating_bucket'] = pd.cut(
    df['delivery_partner_rating'],
    bins=[0, 2, 3.5, 5],
    labels=['Poor', 'Average', 'Good']
)
df[['delivery_partner_rating','partner_rating_bucket']].head(10)

   delivery_partner_rating partner_rating_bucket
0                      3.2               Average
1                      3.2               Average
2                      3.8                  Good
3                      5.0                  Good
4                      4.8                  Good
5                      4.9                  Good
6                      3.7                  Good
7                      4.9                  Good
8                      2.7               Average
9                      4.0                  Good

In [16]:
city_order_count = df['city'].value_counts()
median_count = city_order_count.median()

city_tier_map = city_order_count.apply(lambda x: 'High_Volume' if x > median_count else 'Low_Volume')
df['city_volume_tier'] = df['city'].map(city_tier_map)

df[['city','city_volume_tier']].head(10)

       city city_volume_tier
0     Noida       Low_Volume
1  Amritsar       Low_Volume
2    Mumbai      High_Volume
3     Delhi      High_Volume
4    Mumbai      High_Volume
5   Kolkata       Low_Volume
6  Bengluru      High_Volume
7   Chennai       Low_Volume
8  Bengluru      High_Volume
9   Chennai       Low_Volume

In [17]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in C:\Users\VAGHELA KINJAL\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\VAGHELA KINJAL\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\VAGHELA KINJAL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\VAGHELA KINJAL\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import io, csv, time

# Step 0: Load data
df = pd.read_csv("quick_commerce_data_raw.csv")
print(df.shape)

# Step 1: Connection
username = "postgres"
password = "@Vaghela20"
host = "localhost"
port = 5432
database = "Delivery"

encoded_password = quote_plus(password)
encoded_username = quote_plus(username)

engine = create_engine(
    f"postgresql+psycopg2://{encoded_username}:{encoded_password}@{host}:{port}/{database}"
)

# Step 2: Fast COPY-based insert
def psql_insert_copy(table, conn, keys, data_iter):
    dbapi_conn = conn.connection
    with dbapi_conn.cursor() as cur:
        s_buf = io.StringIO()
        writer = csv.writer(s_buf)
        writer.writerows(data_iter)
        s_buf.seek(0)
        columns = ', '.join(f'"{k}"' for k in keys)
        sql = f'COPY "{table.name}" ({columns}) FROM STDIN WITH CSV'
        cur.copy_expert(sql=sql, file=s_buf)

start = time.time()
with engine.begin() as conn:
    df.to_sql("customer", conn, if_exists="replace", index=False, method=psql_insert_copy)

print(f"Done in {time.time() - start:.2f} seconds")
print("Data successfully loaded into table 'customer' in database 'Delivery'.")

(1000000, 13)
Done in 21.44 seconds
Data successfully loaded into table 'customer' in database 'Delivery'.